name: Code Coverage
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git
        uses: actions/checkout@v2
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@1.1.3
