name: Deploy to Firebase Web Hosting
on:
  push:
    branches: [master]
    paths: ['src/*']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git
        uses: actions/checkout@v2
      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 12
          cache: 'npm'
      - name: Install Packages
        run: npm install
      - name: Build Angular
        run: npm run build
      - name: Deploy to Hosting
        run: |
          npm install -g firebase-tools
          firebase deploy --project "${{ secrets.FIREBASE_PROJECT_ID }}" --token "${{ secrets.FIREBASE_TOKEN }}"
